version: '3.1'
services:
  dfstracker:
    image: season/fastdfs
    command: tracker
    network_mode: host
  storage:
    image: season/fastdfs
    command: tracker
    network_mode: host
    environment:
      TRACKER_SERVER: 192.168.199.174:22122
