version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "25672:25672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
