version: '3.1'
services:
  mysql:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
